server:
  port: 9005
spring:
  application:
    name: web-front-service
polar:
  edge-service-url: ${EDGE_SERVICE_URL:http://localhost:9000}
  auth-service-url: ${AUTH_SERVICE_URL:http://10.0.1.92:9004}
