apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-front-service-bjh
spec:
  selector:
    matchLabels:
      app: web-front-service-bjh
  template:
    metadata:
      labels:
        app: web-front-service-bjh
    spec:
      containers:
        - name: web-front-service-bjh
          image: 879381276515.dkr.ecr.ap-northeast-2.amazonaws.com/front-bjh:latest
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          resources:
            requests:
                cpu: "250m"
                memory: "512Mi"
            limits:
              memory: "1Gi"
              cpu: "500m"
          ports:
          - containerPort: 9005
          env: 
            - name: AUTH_SERVICE_URL
              value: http://auth-service-bjh:80