apiVersion: v1
kind: Service
metadata:
  name: edge-service-bjh
spec:
  type: LoadBalancer
  selector:
    app: edge-service-bjh
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
# type: LoadBalancer -> CLB 생성