apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-bjh
spec:
  selector:
    matchLabels:
      app: auth-service-bjh
  template:
    metadata:
      labels:
        app: auth-service-bjh
    spec:
      containers:
        - name: auth-service-bjh
          image: 879381276515.dkr.ecr.ap-northeast-2.amazonaws.com/auth-bjh:latest
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          resources:
            requests:
                cpu: "250m"
                memory: "512Mi"
            limits:
              memory: "1Gi"
              cpu: "500m"
          ports:
          - containerPort: 9004
          env: 
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://10.0.1.128:3306/auth?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
